// Package project generates the FACT projection of a Go package's
// declaration layer (SPEC §11). The projection is a read-only lens over
// source: navigation questions are answered by grep over the facts, and
// file facts hand off to source for everything statement-level.
//
// Per SPEC §6.4 this generator takes the all-str choice for call edges:
// func:F.calls is list(str) with callees written as the source qualifies
// them ("fmt.Errorf", "ledger.Poster.Post"); no stub facts are emitted.
//
// Scope is a single package directory (test files excluded), loaded and
// type-checked with go/packages, so module-local and module dependencies
// resolve. Declarations whose names are not legal FACT segments (Unicode
// letters, leading underscore) are skipped.
package project

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"

	"flat/fact"
)

// Header is the fixed generated-file marker that begins every stored
// projection file (SPEC §11.1). It is a comment line: parsers ignore it.
const Header = "# Code generated by fact project. DO NOT EDIT."

// CompileError reports that the target package failed to load or
// type-check. Diagnostics preserves every go/packages error
// ("file:line:col: message") so callers — the agent hook above all — can
// surface the full compiler output rather than a lossy summary.
type CompileError struct {
	Target      string
	Diagnostics []string
}

func (e *CompileError) Error() string {
	return fmt.Sprintf("load %s: %s", e.Target, e.Diagnostics[0])
}

// Lines type-checks one Go package and returns its projection as unsorted
// fact lines (SPEC §11.2 vocabulary). Run the result through fact.Parse +
// fact.Validate + fact.Canonical to emit a .fact file.
//
// target is either a package directory, or an import path resolved in the
// current module's context. The latter is how dependencies are projected
// (SPEC §11.5): resolving through the consumer's go.mod pins the version,
// so pkg.version reflects the consumer's dependency graph.
func Lines(target string) ([]string, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedSyntax | packages.NeedModule,
	}
	pattern := target
	if fi, err := os.Stat(target); err == nil && fi.IsDir() {
		cfg.Dir, pattern = target, "."
	}
	pkgs, err := packages.Load(cfg, pattern)
	if err != nil {
		return nil, err
	}
	if len(pkgs) != 1 {
		return nil, fmt.Errorf("%s: expected one package, got %d", target, len(pkgs))
	}
	p := pkgs[0]
	if len(p.Errors) > 0 {
		// go list echoes parse/type errors a second time as list errors
		// (compiler output, "# pkg" prefixed); keep the precise ones.
		precise := false
		for _, pe := range p.Errors {
			if pe.Kind == packages.ParseError || pe.Kind == packages.TypeError {
				precise = true
				break
			}
		}
		ce := &CompileError{Target: target}
		for _, pe := range p.Errors {
			if precise && pe.Kind == packages.ListError {
				continue
			}
			d := pe.Msg
			if pe.Pos != "" && pe.Pos != "-" {
				d = pe.Pos + ": " + d
			}
			ce.Diagnostics = append(ce.Diagnostics, d)
		}
		return nil, ce
	}

	pkg := p.Types
	g := &gen{fset: p.Fset, pkg: pkg, info: p.TypesInfo}
	g.fact("pkg.path", "str", jstr(p.PkgPath))
	if p.Module != nil && p.Module.Version != "" { // versioned (third-party) module, SPEC §11.5
		g.fact("pkg.version", "str", jstr(p.Module.Version))
	}
	g.collect(p.Syntax)

	// In-scope interfaces (≥1 method) for computed satisfaction facts.
	var ifaces []*types.Named
	var named []*types.Named
	for _, name := range pkg.Scope().Names() {
		tn, ok := pkg.Scope().Lookup(name).(*types.TypeName)
		if !ok || tn.IsAlias() || !fact.IsSegment(name) {
			continue
		}
		n, ok := tn.Type().(*types.Named)
		if !ok {
			continue
		}
		named = append(named, n)
		if iface, ok := n.Underlying().(*types.Interface); ok && iface.NumMethods() > 0 {
			ifaces = append(ifaces, n)
		}
	}
	for _, n := range named {
		g.typeFacts(n, ifaces)
		g.methodFacts(n)
	}
	for _, name := range pkg.Scope().Names() {
		if fn, ok := pkg.Scope().Lookup(name).(*types.Func); ok && fact.IsSegment(name) {
			g.funcFacts(fn)
		}
	}
	return g.lines, nil
}

type gen struct {
	fset  *token.FileSet
	pkg   *types.Package
	info  *types.Info
	lines []string
	// bodies maps top-level functions to their AST bodies for call edges.
	bodies map[types.Object]*ast.BlockStmt
}

func (g *gen) fact(key, typ, val string) {
	g.lines = append(g.lines, key+": "+typ+" = "+val)
}

// qual renders types as the source qualifies them: bare in-package,
// package-name-prefixed otherwise.
func (g *gen) qual(p *types.Package) string {
	if p == g.pkg {
		return ""
	}
	return p.Name()
}

// file names the source file declaring pos. Deliberately no line number:
// the churn invariant (SPEC §11.2) requires the projection to change iff
// the declaration layer changes, and line numbers churn under body edits.
func (g *gen) file(pos token.Pos) string {
	return filepath.Base(g.fset.Position(pos).Filename)
}

// collect emits the imports fact and indexes function bodies for call edges.
func (g *gen) collect(files []*ast.File) {
	g.bodies = map[types.Object]*ast.BlockStmt{}
	for _, f := range files {
		for _, decl := range f.Decls {
			if fd, ok := decl.(*ast.FuncDecl); ok && fd.Recv == nil {
				g.bodies[g.info.Defs[fd.Name]] = fd.Body
			}
		}
	}
	var paths []string
	for _, imp := range g.pkg.Imports() {
		paths = append(paths, imp.Path())
	}
	sort.Strings(paths)
	g.fact("imports", "list(str)", strList(paths))
}

func (g *gen) typeFacts(n *types.Named, ifaces []*types.Named) {
	name := n.Obj().Name()
	k := "type:" + name
	under := n.Underlying()

	kind := "basic"
	switch under.(type) {
	case *types.Struct:
		kind = "struct"
	case *types.Interface:
		kind = "iface"
	}
	g.fact(k+".kind", "enum(struct|iface|basic)", kind)
	g.fact(k+".file", "str", jstr(g.file(n.Obj().Pos())))

	if st, ok := under.(*types.Struct); ok {
		var fields []string
		for i := 0; i < st.NumFields(); i++ {
			f := st.Field(i)
			if !fact.IsSegment(f.Name()) {
				continue
			}
			fields = append(fields, f.Name())
			g.fact(k+".field_"+f.Name()+"_type", "str", jstr(types.TypeString(f.Type(), g.qual)))
		}
		g.fact(k+".fields", "list(str)", strList(fields))
	}

	// Method set: pointer-receiver superset for concrete types.
	recv := types.Type(types.NewPointer(n))
	if _, ok := under.(*types.Interface); ok {
		recv = n
	}
	ms := types.NewMethodSet(recv)
	var methods []string
	for i := 0; i < ms.Len(); i++ {
		if m := ms.At(i).Obj(); fact.IsSegment(m.Name()) {
			methods = append(methods, m.Name())
		}
	}
	sort.Strings(methods)
	g.fact(k+".methods", "list(str)", strList(methods))

	// Computed interface satisfactions — the query grep cannot answer
	// from source (SPEC §1.1).
	var impl []string
	for _, in := range ifaces {
		if in == n {
			continue
		}
		iface := in.Underlying().(*types.Interface)
		if types.Implements(n, iface) || types.Implements(types.NewPointer(n), iface) {
			impl = append(impl, "type:"+in.Obj().Name())
		}
	}
	sort.Strings(impl)
	g.fact(k+".implements", "list(ref(type))", "["+strings.Join(impl, ", ")+"]")

	if iface, ok := under.(*types.Interface); ok {
		for i := 0; i < iface.NumMethods(); i++ {
			m := iface.Method(i)
			if !fact.IsSegment(m.Name()) {
				continue
			}
			g.fact(k+".method_"+m.Name()+"_sig", "str", jstr(types.TypeString(m.Type(), g.qual)))
		}
	}
}

func (g *gen) methodFacts(n *types.Named) {
	name := n.Obj().Name()
	for i := 0; i < n.NumMethods(); i++ {
		m := n.Method(i)
		if !fact.IsSegment(m.Name()) {
			continue
		}
		k := "method:" + name + "_" + m.Name()
		g.fact(k+".sig", "str", jstr(types.TypeString(m.Type(), g.qual)))
		g.fact(k+".file", "str", jstr(g.file(m.Pos())))
		g.fact(k+".receiver", "str", jstr(name))
	}
}

func (g *gen) funcFacts(f *types.Func) {
	k := "func:" + f.Name()
	g.fact(k+".sig", "str", jstr(types.TypeString(f.Type(), g.qual)))
	g.fact(k+".file", "str", jstr(g.file(f.Pos())))
	g.fact(k+".exported", "bool", strconv.FormatBool(f.Exported()))
	g.fact(k+".calls", "list(str)", strList(g.calls(g.bodies[f])))
}

// calls resolves the static callees of body, sorted and deduplicated.
func (g *gen) calls(body *ast.BlockStmt) []string {
	if body == nil {
		return nil
	}
	set := map[string]bool{}
	ast.Inspect(body, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok {
			return true
		}
		var obj types.Object
		switch fun := ast.Unparen(call.Fun).(type) {
		case *ast.Ident:
			obj = g.info.Uses[fun]
		case *ast.SelectorExpr:
			if sel, ok := g.info.Selections[fun]; ok {
				obj = sel.Obj()
			} else {
				obj = g.info.Uses[fun.Sel] // package-qualified call: pkg.F()
			}
		}
		if f, ok := obj.(*types.Func); ok {
			set[g.callee(f)] = true
		}
		return true
	})
	out := make([]string, 0, len(set))
	for c := range set {
		out = append(out, c)
	}
	sort.Strings(out)
	return out
}

// callee names f as source qualifies it: "F", "T.M", "pkg.F", "pkg.T.M".
// Through interfaces this is the static callee (e.g. "ledger.Poster.Post").
func (g *gen) callee(f *types.Func) string {
	name := f.Name()
	pkg := f.Pkg()
	if recv := f.Type().(*types.Signature).Recv(); recv != nil {
		t := recv.Type()
		if ptr, ok := t.(*types.Pointer); ok {
			t = ptr.Elem()
		}
		if n, ok := t.(*types.Named); ok {
			name = n.Obj().Name() + "." + name
			pkg = n.Obj().Pkg()
		}
	}
	if pkg != nil && pkg != g.pkg {
		name = pkg.Name() + "." + name
	}
	return name
}

// jstr renders s as a FACT str value (JSON string literal).
func jstr(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// strList renders a list(str) value from raw strings.
func strList(ss []string) string {
	toks := make([]string, len(ss))
	for i, s := range ss {
		toks[i] = jstr(s)
	}
	return "[" + strings.Join(toks, ", ") + "]"
}
